# Generated by Django 4.2 on 2023-05-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
