# Generated by Django 4.2 on 2023-05-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0005_footgallery_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footgallery',
            new_name='Footgallerie',
        ),
    ]
