# Generated by Django 4.2 on 2023-05-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0006_rename_footgallery_footgallerie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
