# Generated by Django 4.2 on 2023-05-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0007_alter_newsletter_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(choices=[('BD', 'Backend with Django'), ('FD', 'Frontend Design'), ('PD', 'Product Design')], max_length=10)),
                ('cohort', models.CharField(choices=[('BD', 'Backend with Django'), ('FD', 'Frontend Design'), ('PD', 'Product Design')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='instruction',
        ),
    ]
